main:
  #номер ID админа
  admin: 148861643
  #путь к папке с файлами октопринта
  filesdir:
  #ключ для апи октопринта
  key: 17D2725AF03C4F6999ED90B0ADFAD319
  #url октопринта
  octoprint: http://127.0.0.1:5000
  #токен бота для телеграма
  token: 1015881710:AAGKiE50pfMX6gUj30Mk-MTfgp1Hox724sU
misc:
  #уведомления по событиям
  events:
    #полная тишина отправки сообщений
    full_silent: false
    #уведомление на изменение слоя печати
    z_change:
      #включено ли это событие
      enable: true
      #безшумное сообщение
      silent: true
      #минимальный интервал отправки сообщения о смене слоя
      min_seconds: 30
      #минимальный интервал в мм по высоте на отправку сообщения
      min_mm: 1
      #отправка фотографий
      photos:
        #отправлять ли фотографии
        enable: true
        #отправлять ли с одной камеры
        one_cam: true
        #название камеры со списка камер
        camera: M2Mini
      #какая информация включена в сообщение
      information:
        #включена ли вообще отправка текстом информации
        enable: true
        #отправлять ли полную информацию
        full_info: false
        #элементы статуса для отправки
        items: [printer_status, hotbed_temp, hotbed_temp_target, hotbed_temp_delta,
          extruder_temp, extruder_t emp_target, extruder_temp_delta, printing_status,
          print_file_name, time_print_start, time_print_calculated, height_current,
          height_max, height_percentage, height_left, layer_current, layer_max, layer_percentage,
          layer_left, layer_time, filament_calculated_length, filament_calculated_weight,
          filament_calculated_volume, byte_progress, byte_max, byte_percentage, time_print,
          time_print_left, time_print_end, additional_info]
    #уведомление на команду статуса 
    status:
      #включено ли это событие
      enable: true
      #безшумное сообщение
      silent: true
      #минимальный интервал отправки сообщения о смене слоя
      min_seconds: 30
      #минимальный интервал в мм по высоте на отправку сообщения
      min_mm: 1
      #отправка фотографий
      photos:
        #отправлять ли фотографию
        enable: true
        #какая информация включена в сообщение
      information:
        #включена ли вообще отправка текстом информации
        enable: true
        #отправлять ли полную информацию
        full_info: false
        #элементы статуса для отправки
        items: [printer_status, hotbed_temp, hotbed_temp_target, hotbed_temp_delta,
          extruder_temp, extruder_temp_target, extruder_temp_delta, printing_status,
          print_file_name, time_print_start, time_print_calculated, height_current,
          height_max, height_percentage, height_left, layer_current, layer_max, layer_percentage,
          layer_left, layer_time, filament_calculated_length, filament_calculated_weight,
          filament_calculated_volume, byte_progress, byte_max, byte_percentage, time_print,
          time_print_left, time_print_end, additional_info]
  #общие элементы статуса для отправки
  status_items:
    printer_status: true
    hotbed_temp: true
    hotbed_temp_target: true
    hotbed_temp_delta: true
    extruder_temp: true
    extruder_temp_target: true
    extruder_temp_delta: true
    printing_status: true
    print_file_name: true
    time_print_start: true
    time_print_calculated: true
    height_current: true
    height_max: true
    height_percentage: true
    height_left: true
    layer_current: true
    layer_max: true
    layer_percentage: true
    layer_left: true
    layer_time: true
    filament_calculated_length: true
    filament_calculated_weight: true
    filament_calculated_volume: true
    byte_progress: true
    byte_max: true
    byte_percentage: true
    time_print: true
    time_print_left: true
    time_print_end: true
    additional_info: true
 
#настройки принтера
printer:
  #фото
  photo:
    #включена ли возможность фото
    enable: true
    #скрипт на снятие фотографий
    script: 'bash photo.sh'
    #входной файл с общей фото
    file: 'photo.jpg'
  #количество экструдеров
  extruders: 1
  #финишная высота парковки оси Z
  max_z_finish: 230
  #температура охлаждения после которой бот выдаст сообщение. используется чтоб деталь остыла после печати. если не нужно, то поставить -1
  cooldown_hotbed_temp: 50
system:
  abort_button:
    enable: true
    command: custom/printer_off
