main:
  admin: 148861643
  filesdir: null
  key: 17D2725AF03C4F6999ED90B0ADFAD319
  octoprint: http://192.168.1.30:5000
  token: 1015881710:AAGKiE50pfMX6gUj30Mk-MTfgp1Hox724sU
misc:
  silent: false
  silent_photos: true
  silent_z_change: true
  notify:
    z_change:
      enable: true
      min_seconds: 10
      min_mm: 0
  status_items:
    printer_status: true
    hotbed_temp: true
    hotbed_temp_target: true
    hotbed_temp_delta: true
    extruder_temp: true
    extruder_temp_target: true
    extruder_temp_delta: true
    printing_status: true
    print_file_name: true
    time_print_start: true
    time_print_calculated: true
    height_current: true
    height_max: true
    height_percentage: true
    height_left: true
    layer_current: true
    layer_max: true
    layer_percentage: true
    layer_left: true
    layer_time:true
    filament_calculated_length: true
    filament_calculated_weight: true
    filament_calculated_volume: true
    byte_progress: true
    byte_max: true
    byte_percentage: true
    time_print: true
    time_print_left: true
    time_print_end: true
    additional_info: true
printer:
  cam_count: 2
  cameras:
  - Mi5:
      name: Фронтальная
      photo_url: /photoaf.jpg
      ptz_controls: true
      type: android_ipwebcam
      url: http://192.168.1.75:5000
      video_url: /video
  - M2Mini:
      name: Сверху
      photo_url: /photoaf.jpg
      ptz_controls: true
      type: android_ipwebcam
      url: http://192.168.1.159:5000
      video_url: /video
  - Z007:
      name: Сбоку
      photo_url: /photoaf.jpg
      ptz_controls: true
      type: android_ipwebcam
      url: http://192.168.1.159:5000
      video_url: /video
  - usbcam:
      name: Сопло
      file_path: usbcam.jpg
      script: photo.sh
      type: shell_script_image
  extruders: 1
  max_z_finish: 230
system:
  enable_system_commands: true
  abort_button:
    enable: true
    command: custom/printer_off
