#This file was originally generated by PyScripter's unit test wizard

import unittest
import octobot

class TestGlobalFunctions(unittest.TestCase):

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testparse_file_for_offsets(self):
        pass

    def testget_current_z_pos(self):
        pass

if __name__ == '__main__':
    unittest.main()
